# (c) https://github.com/MontiCore/monticore
image: registry.git.rwth-aachen.de/monticore/container-registry/maven:3-jdk-8

#include:
#  - template: Code-Quality.gitlab-ci.yml
#
variables:
  MC_MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2"
  GRADLE_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2"
  MC_MAVEN_CLI_OPTS: "--settings settings.xml --batch-mode -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"


before_script:
  - chmod +x ./gradlew
  - chmod +x monticore-tool/gradlew
  - export GRADLE_USER_HOME=`pwd`/.gradle

#cache:
#  paths:
#    - .m2/
#    - .gradle/wrapper
#  key: ${CI_COMMIT_REF_SLUG} # Cache per branch

stages:
  - build
  - test
  - deploy
  - trigger_languages
  - report

build:
  stage: build
  script:
    - "cd monticore-tool && ./gradlew build $GRADLE_OPTS -Pci"
    - "cd .. &&./gradlew buildMC $GRADLE_OPTS -Pci"
  artifacts: 
    paths:
      - ".gradle"
      - "*/target"
      - "*/.gradle"
    expire_in: 1 week
  only:
    - merge_requests
    - branches
  except:
    - master
    
test_01experiments:
  stage: test
  dependencies:
    - build
  script:
    - "./gradlew -p monticore-test/01.experiments build $GRADLE_OPTS"
  only:
    - merge_requests
    - branches
  except:
    - master
    
test_02experiments:
  stage: test
  dependencies:
    - build
  script:
    - "./gradlew -p monticore-test/02.experiments build $GRADLE_OPTS"
  only:
    - merge_requests
    - branches
  except:
    - master
    
test_it:
  stage: test
  dependencies:
    - build
  script:
    - "./gradlew -p monticore-test/it build $GRADLE_OPTS"
  only:
    - merge_requests
    - branches
  except:
    - master
    
test_it_emf:
  stage: test
  dependencies:
    - build
  script:
    - "./gradlew -p monticore-test/it build -PbuildProfile=emf $GRADLE_OPTS"
  only:
    - merge_requests
    - branches
  except:
    - master
    
test_grammar_it:
  stage: test
  dependencies:
    - build
  script:
    - "./gradlew -p monticore-test/monticore-grammar-it build $GRADLE_OPTS"
  only:
    - merge_requests
    - branches
  except:
    - master
    
deploy:
  stage: deploy
  dependencies:
    - build
  script:
    - "./gradlew deployMC -PmavenPassword=$password -PmavenUser=$username $GRADLE_OPTS"
  only:
    - dev
  except:
    - master
      
build_maven:
  stage: build
  script:
    - "mvn $MC_MAVEN_CLI_OPTS $MC_MAVEN_OPTS install"
  only:
    - schedules
  except:
    - master

trigger-automata:
  stage: trigger_languages
  allow_failure: true
  trigger:
    project: monticore/languages/automaton
    branch: master
    strategy: depend
  only:
    - dev

trigger-cd4a-dev:
  stage: trigger_languages
  trigger:
    project: monticore/cd4analysis/cd4analysis
    branch: develop
  only:
    - dev

trigger-sd-dev:
  stage: trigger_languages
  trigger:
    project: monticore/statechart/sd-language
    branch: dev
  only:
    - dev

trigger-fd-dev:
  stage: trigger_languages
  trigger:
    project: monticore/languages/feature-diagram
    branch: develop
  only:
    - dev

trigger-guidsl-dev:
  stage: trigger_languages
  trigger:
    project: monticore/languages/gui-dsl
    branch: master
  only:
    - dev

trigger-json-dev:
  stage: trigger_languages
  trigger:
    project: monticore/languages/json
    branch: develop
  only:
    - dev

trigger-ma-dev:
  stage: trigger_languages
  trigger:
    project: monticore/montiarc/core
    branch: develop
  only:
    - dev

trigger-ocl-dev:
  stage: trigger_languages
  trigger:
    project: monticore/languages/OCL
    branch: develop
  only:
    - dev

trigger-siunits-dev:
  stage: trigger_languages
  trigger:
    project: monticore/languages/siunits
    branch: dev
  only:
    - dev

trigger-sc-dev:
  stage: trigger_languages
  trigger:
    project: monticore/statechart/sc-language
    branch: dev
  only:
    - dev

trigger-xml-dev:
  stage: trigger_languages
  trigger:
    project: monticore/languages/xml
    branch: develop
  only:
    - dev

trigger-od-dev:
  stage: trigger_languages
  trigger:
    project: monticore/languages/od
    branch: dev
  only:
    - dev

trigger-cd4a-master:
  stage: trigger_languages
  trigger:
    project: monticore/cd4analysis/cd4analysis
    branch: master
  only:
    - master

trigger-sd-master:
  stage: trigger_languages
  trigger:
    project: monticore/statechart/sd-language
    branch: master
  only:
    - master

trigger-fd-master:
  stage: trigger_languages
  trigger:
    project: monticore/languages/feature-diagram
    branch: master
  only:
    - master

trigger-guidsl-master:
  stage: trigger_languages
  trigger:
    project: monticore/languages/gui-dsl
    branch: master
  only:
    - master

trigger-json-master:
  stage: trigger_languages
  trigger:
    project: monticore/languages/json
    branch: master
  only:
    - master

trigger-ma-master:
  stage: trigger_languages
  trigger:
    project: monticore/montiarc/core
    branch: master
  only:
    - master

trigger-ocl-master:
  stage: trigger_languages
  trigger:
    project: monticore/languages/OCL
    branch: master
  only:
    - master

trigger-siunits-master:
  stage: trigger_languages
  trigger:
    project: monticore/languages/siunits
    branch: master
  only:
    - master

trigger-sc-master:
  stage: trigger_languages
  trigger:
    project: monticore/statechart/sc-language
    branch: master
  only:
    - master

trigger-xml-master:
  stage: trigger_languages
  trigger:
    project: monticore/languages/xml
    branch: master
  only:
    - master

trigger-od-master:
  stage: trigger_languages
  trigger:
    project: monticore/languages/od
    branch: master
  only:
    - master

pages:
  stage: report
  dependencies: []
  image: python:alpine
  before_script:
    - apk add gcc musl-dev python3-dev
    - pip install cython
    - pip install mkdocs
    - pip install mkdocs-material
  script:
    - sh docs/scripts/preprocessing.sh
    - mkdocs build
    - mv site public
  artifacts:
    paths:
      - public
  only:
    - schedules